# Generated by Django 4.1.7 on 2023-03-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('muscle_type', models.CharField(choices=[('ABDOMINAL', 'Abdominal'), ('LOWER_BACK', 'Lower back'), ('UPPER_BACK', 'Upper Back'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('CHEST', 'Chest'), ('CALVES', 'Calves'), ('FOREARMS', 'Forearms'), ('GLUTES', 'Glutes'), ('HAMSTRINGS', 'Hamstrings'), ('LATS', 'Lats'), ('SHOULDERS', 'Shoulders'), ('TRAPS', 'Traps'), ('QUADRICEPS', 'Quadriceps'), ('FBW', 'Full body workout')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('createdBy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=50, null=True)),
                ('exercises', models.ManyToManyField(blank=True, through='workouts.ExerciseDetails', to='workouts.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercisedetails',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
