# Generated by Django 5.0.6 on 2024-08-29 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('muscle_type', models.CharField(choices=[('ABDOMINAL', 'Abdominal'), ('LOWER_BACK', 'Lower back'), ('UPPER_BACK', 'Upper Back'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('CHEST', 'Chest'), ('CALVES', 'Calves'), ('FOREARMS', 'Forearms'), ('GLUTES', 'Glutes'), ('HAMSTRINGS', 'Hamstrings'), ('LATS', 'Lats'), ('SHOULDERS', 'Shoulders'), ('TRAPS', 'Traps'), ('QUADRICEPS', 'Quadriceps'), ('FBW', 'Full body workout')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='exercises/')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workouts.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, through='workouts.WorkoutDetails', to='workouts.exercise'),
        ),
    ]
