# Generated by Django 5.0.6 on 2024-09-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_workout_createdat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="description",
        ),
        migrations.AddField(
            model_name="workoutdetails",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
