# Generated by Django 5.0.6 on 2024-06-17 18:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('fav_exercises', models.ManyToManyField(blank=True, to='workouts.exercise')),
                ('workouts', models.ManyToManyField(blank=True, to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(validators=[django.core.validators.RegexValidator(regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*\\W).{8,50}$')])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
